### ISSUE TITLE
Food Storage Name is displayed as ---MISSING--- and has no icon

### ISSUE THREAD

**Issue by Maxwelllondon92** [benediktwerner/Stacklands-CompactStorage-Mod#1]
![image](https://user-images.githubusercontent.com/48402058/201468143-ef2475c0-8579-4159-b4aa-b4a987cc8775.png)

**Comment by benediktwerner** [comment]
Ah, I didn't think the game would still load English first even if you have another language selected so it didn't insert the terms correctly. Should now work with other languages as well if you update to the latest version.
