### ISSUE TITLE
Stacked wharehouse idea is errored

### ISSUE THREAD

**Issue by Anonymous-02** [benediktwerner/Stacklands-CompactStorage-Mod#2]
when i first got the idea it was all grey, I quit and relogged to see if it would solve anything 
and ended up with this texture :
![Capture d’écran 2022-11-13 183212](https://user-images.githubusercontent.com/62241664/201535705-db9b7e9d-1088-4052-85c7-8da221fdadff.png)
and when hovering it, instead of the recipe, all I got was "--MISSING--"
and the bepinex console repeatedly showed this error 
![Capture d’écran 2022-11-13 183233](https://user-images.githubusercontent.com/62241664/201535882-7e0934de-1305-49ba-9292-e11f03294404.png)

**Comment by benediktwerner** [comment]
Are you on the latest version of the game? It looks like your game doesn't know about magic dust which was added in the witch forest update.

**Comment by Anonymous-02** [comment]
you're right, I just updated and it works fine
