### ISSUE TITLE
Can't Take Items Out of Magic Pouch

### ISSUE THREAD

**Issue by DizzyDJW** [benediktwerner/Stacklands-CompactStorage-Mod#3]
Latest version: 1.0.6

Could be an issue with another mod not being compatible, but these are all the same mods I've had for a while, just updated. They worked fine together before, without issue.

- BepInEx
- BerryLoader
- BugFixes
- HigherSidebar
- BetterInfo
- BetterCrane (New)
- GolemAutomation
- Infinite_Save_Files
- CompactStorage
- FasterEndOfMonths
- Show_Actual_Available_Food
- BetterMouseControls
- CardZones
- BottledTime
- Stack_Further

**Comment by benediktwerner** [comment]
Does this still happen? It works fine for me but I'm not using all those mods on the list, so presumably, one of those is interfering.
