### ISSUE TITLE
Steam workshop's version need to be update

### ISSUE THREAD

**Issue by CypressVillage** [benediktwerner/Stacklands-CompactStorage-Mod#5]
## problem

Thanks for providing such a convinent mod! I noticed that the mod on steam workshop has bugs now. **The magic_pouch cannot pop up cards from the pouch though it contains cards.** 

## solution
I tried to solve the problem and found that your mod cannot find the official function's address. Since sockpop released a new DLC: StackLand 2000, it seems that they recompiled their gamescript, which may cause that problem. I rebuild a dll from source and the problem solved. So please upload a recompiled version on steam to fix the problem. Best wishes!

## other confuse

When I build the mod, I got some problems but I'm not sure is there some settings I didn't done:

- line 92 in MagicPouch.cs, the compilor said it wants a `UnityEngine.Vector3` but got `null`, I read decompiled codes in gamescripts.dll, it surely needs a vector but not used. so I put a new UnityEngine.Vector3 into the parameter instead of null.
- property `GAME_DATA_PATH` is lost so I add one in `CompactStorage\src\CompactStorage.csproj.user` myself.

My compile env is Visual Studio 2022

**Comment by benediktwerner** [comment]
Thanks for the detailed report, finally found some time to look at this and uploaded a fixed version of the mod.

The `GAMEP_DATA_PATH` property should be set automatically in the csproj file but I guess I haven't tried it on Windows in a long time so maybe it's not working anymore 🤔 But I guess setting it manually is a reasonable solution.
